/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycom.mytest1.view;

/**
 *
 * @author kaushika
 */
public class CreditDetails extends javax.swing.JPanel {

    /**
     * Creates new form CreditDetails
     */
    public CreditDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInNumber = new javax.swing.JLabel();
        jTextFieldjLabelInNumber = new javax.swing.JTextField();
        jLabelCreditCusName = new javax.swing.JLabel();
        jTextFieldCreditCusName = new javax.swing.JTextField();
        jLabelCreditCusTP = new javax.swing.JLabel();
        jTextFieldCreditCusTP = new javax.swing.JTextField();
        jLabelCreditCusAddress = new javax.swing.JLabel();
        jTextFieldlCreditCusAddress = new javax.swing.JTextField();
        jLabelCreditDate = new javax.swing.JLabel();
        jDateChooserCreditDate = new com.toedter.calendar.JDateChooser();
        jLabelCreditHeading = new javax.swing.JLabel();
        jButtonCreditAdd = new javax.swing.JButton();

        jLabelInNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelInNumber.setText("Invoice Number");

        jLabelCreditCusName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCreditCusName.setText("Customer Name");

        jLabelCreditCusTP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCreditCusTP.setText("Customer TP");

        jLabelCreditCusAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCreditCusAddress.setText("Address");

        jLabelCreditDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCreditDate.setText("Date");

        jLabelCreditHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCreditHeading.setText("Credit Details");

        jButtonCreditAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCreditAdd.setText("Add");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCreditAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelCreditDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCreditCusAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCreditCusName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addComponent(jLabelInNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCreditCusTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldjLabelInNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCreditCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldlCreditCusAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCreditCusTP, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jDateChooserCreditDate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(jLabelCreditHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCreditHeading)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInNumber)
                    .addComponent(jTextFieldjLabelInNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCreditCusName)
                    .addComponent(jTextFieldCreditCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCreditCusTP)
                    .addComponent(jTextFieldCreditCusTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCreditCusAddress)
                    .addComponent(jTextFieldlCreditCusAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCreditDate)
                    .addComponent(jDateChooserCreditDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButtonCreditAdd)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreditAdd;
    private com.toedter.calendar.JDateChooser jDateChooserCreditDate;
    private javax.swing.JLabel jLabelCreditCusAddress;
    private javax.swing.JLabel jLabelCreditCusName;
    private javax.swing.JLabel jLabelCreditCusTP;
    private javax.swing.JLabel jLabelCreditDate;
    private javax.swing.JLabel jLabelCreditHeading;
    private javax.swing.JLabel jLabelInNumber;
    private javax.swing.JTextField jTextFieldCreditCusName;
    private javax.swing.JTextField jTextFieldCreditCusTP;
    private javax.swing.JTextField jTextFieldjLabelInNumber;
    private javax.swing.JTextField jTextFieldlCreditCusAddress;
    // End of variables declaration//GEN-END:variables
}
