/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycom.mytest1.view;

import com.mycom.mytest1.model.Category;
import com.mycom.mytest1.model.DB;

import com.sun.org.apache.xalan.internal.xsltc.compiler.util.StringStack;
import java.util.List;
import java.awt.TextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static java.sql.Types.DOUBLE;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kaushika
 */
public class InvoiceManager extends javax.swing.JPanel {
    static boolean f = true;
     //private static final Logger logger=Logger.getLogger(InvoiceManager.class);
     static org.apache.log4j.Logger logger=org.apache.log4j.Logger.getLogger(InvoiceManager.class);
    /**
     * Creates new form InvoiceManager
     */
    public InvoiceManager() {
        initComponents();
        selectCategory();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabeChequeOtherDetails = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDialog2 = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelInvoiceNumber = new javax.swing.JLabel();
        jTextFieldInvoiceNumber = new javax.swing.JTextField();
        jLabelDate = new javax.swing.JLabel();
        jDateChooserInDate = new com.toedter.calendar.JDateChooser();
        jLabelCusName = new javax.swing.JLabel();
        jTextFieldCusName = new javax.swing.JTextField();
        jLabelCategory = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox();
        jLabelPurchasePrice = new javax.swing.JLabel();
        jTextFieldPurchasePrice = new javax.swing.JTextField();
        jLabelSellingPrice = new javax.swing.JLabel();
        jLabelWarranty = new javax.swing.JLabel();
        jComboBoxWarranty = new javax.swing.JComboBox();
        jLabelName = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jButtonAddList = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jRadioButtonCheque = new javax.swing.JRadioButton();
        jRadioButtonCredit = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelCode = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jPanelShowHide = new javax.swing.JPanel();
        jLabelInvoiceIME = new javax.swing.JLabel();
        jTextFieldInvoiceIME = new javax.swing.JTextField();
        jLabelBrandName = new javax.swing.JLabel();
        jLabelInvoiceModel = new javax.swing.JLabel();
        jTextFieldlInvoiceModel = new javax.swing.JTextField();
        jTextFieldBrandName = new javax.swing.JTextField();
        jLabellInvoiceNumber1 = new javax.swing.JLabel();
        jTextFieldlInvoiceNumber1 = new javax.swing.JTextField();
        jLabelInvoiceAddress = new javax.swing.JLabel();
        jTextFieldInvoiceAddress = new javax.swing.JTextField();
        jLabelInvoiceContact = new javax.swing.JLabel();
        jTextFieldInvoiceContact = new javax.swing.JTextField();
        jPanelItem = new javax.swing.JPanel();
        jLabelItemName = new javax.swing.JLabel();
        jTextFieldItemName = new javax.swing.JTextField();
        jPanelQuantity = new javax.swing.JPanel();
        jTextFieldInvoiceQuantity = new javax.swing.JTextField();
        jLabelInvoiceQuantity = new javax.swing.JLabel();
        jTextFieldUnitPrice = new javax.swing.JTextField();

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButton1.setText("Add Cheque Details");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cheque Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Cheque Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Bank");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Branch");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Amount");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Cheque Payement");

        jLabeChequeOtherDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeChequeOtherDetails.setText("Other Details");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabeChequeOtherDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jToggleButton1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(111, 397, Short.MAX_VALUE))))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addGap(57, 57, 57)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabeChequeOtherDetails))
                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Debtors Details");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Debtor Name");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Address");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("TP Number");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Amount");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Add Debtor");

        jLabelInvoiceNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelInvoiceNumber.setText("Invoice Number");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1)
                        .addGroup(jDialog2Layout.createSequentialGroup()
                            .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField3)
                                .addComponent(jTextField8)
                                .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialog2Layout.createSequentialGroup()
                            .addComponent(jLabelInvoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldInvoiceNumber))))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(32, 32, 32)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInvoiceNumber)
                    .addComponent(jTextFieldInvoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addGap(60, 60, 60))
        );

        jLabelDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDate.setText("Date");

        jLabelCusName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCusName.setText("Customer Name");

        jTextFieldCusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCusNameActionPerformed(evt);
            }
        });

        jLabelCategory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCategory.setText("Category");

        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Phones", "Charger", "Battery", "Head Phone", "Phone Pouch", "Phone Housing" }));
        jComboBoxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryActionPerformed(evt);
            }
        });

        jLabelPurchasePrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurchasePrice.setText("Purchase Price");

        jTextFieldPurchasePrice.setEditable(false);
        jTextFieldPurchasePrice.setBackground(new java.awt.Color(215, 207, 205));
        jTextFieldPurchasePrice.setText("2500");
        jTextFieldPurchasePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPurchasePriceActionPerformed(evt);
            }
        });

        jLabelSellingPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSellingPrice.setText("Unit Price");

        jLabelWarranty.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelWarranty.setText("Warranty");

        jComboBoxWarranty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Warranty", "6 months", "1 year", "2 years", " " }));
        jComboBoxWarranty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxWarrantyActionPerformed(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelName.setText("Seeling Invoice");

        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonAddList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAddList.setText("Add To List");
        jButtonAddList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddListActionPerformed(evt);
            }
        });

        jButtonPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPrint.setText("Generate invoice");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTotal.setText("Total");

        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCheque);
        jRadioButtonCheque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonCheque.setText("Cheque Payment");
        jRadioButtonCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonChequeActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCredit);
        jRadioButtonCredit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonCredit.setText("Credit");
        jRadioButtonCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCreditActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Description", "Quantity", "Unit_Price", "Amount", "Warranty", "IMEI _Number", "Model", "Brand_name", "Item_Name", "Category_id", "item_code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabelCode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCode.setText("Code");

        jTextFieldCode.setEditable(false);
        jTextFieldCode.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCode.setText("NE99");
        jTextFieldCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeActionPerformed(evt);
            }
        });

        jLabelInvoiceIME.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelInvoiceIME.setText("IMEI Number");

        jTextFieldInvoiceIME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInvoiceIMEActionPerformed(evt);
            }
        });

        jLabelBrandName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBrandName.setText("Brand Name");

        jLabelInvoiceModel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelInvoiceModel.setText("Model");

        jTextFieldBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBrandNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelShowHideLayout = new javax.swing.GroupLayout(jPanelShowHide);
        jPanelShowHide.setLayout(jPanelShowHideLayout);
        jPanelShowHideLayout.setHorizontalGroup(
            jPanelShowHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowHideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelShowHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelInvoiceIME, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jTextFieldInvoiceIME))
                .addGroup(jPanelShowHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelShowHideLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldlInvoiceModel, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShowHideLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelInvoiceModel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelShowHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBrandName)
                    .addComponent(jTextFieldBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanelShowHideLayout.setVerticalGroup(
            jPanelShowHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowHideLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelShowHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInvoiceIME)
                    .addComponent(jLabelBrandName)
                    .addComponent(jLabelInvoiceModel))
                .addGap(18, 18, 18)
                .addGroup(jPanelShowHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInvoiceIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldlInvoiceModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabellInvoiceNumber1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabellInvoiceNumber1.setText("Invoice Number");

        jTextFieldlInvoiceNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldlInvoiceNumber1ActionPerformed(evt);
            }
        });

        jLabelInvoiceAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelInvoiceAddress.setText("Address");

        jLabelInvoiceContact.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelInvoiceContact.setText("Contact Number");

        jLabelItemName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelItemName.setText("Item Name");

        javax.swing.GroupLayout jPanelItemLayout = new javax.swing.GroupLayout(jPanelItem);
        jPanelItem.setLayout(jPanelItemLayout);
        jPanelItemLayout.setHorizontalGroup(
            jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldItemName)
                    .addGroup(jPanelItemLayout.createSequentialGroup()
                        .addComponent(jLabelItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 76, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelItemLayout.setVerticalGroup(
            jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelItemName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jTextFieldItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTextFieldInvoiceQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInvoiceQuantityActionPerformed(evt);
            }
        });

        jLabelInvoiceQuantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelInvoiceQuantity.setText("Quantity");

        javax.swing.GroupLayout jPanelQuantityLayout = new javax.swing.GroupLayout(jPanelQuantity);
        jPanelQuantity.setLayout(jPanelQuantityLayout);
        jPanelQuantityLayout.setHorizontalGroup(
            jPanelQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuantityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldInvoiceQuantity)
                    .addComponent(jLabelInvoiceQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelQuantityLayout.setVerticalGroup(
            jPanelQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQuantityLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabelInvoiceQuantity)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldInvoiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTextFieldUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUnitPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(326, 326, 326))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabellInvoiceNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldlInvoiceNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInvoiceContact)
                            .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(530, 530, 530))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonCheque)
                        .addGap(446, 446, 446))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelInvoiceAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldInvoiceAddress))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelCusName)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPanelShowHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanelItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabelCode, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jPanelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonAddList)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBoxWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldInvoiceContact, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRadioButtonCredit)
                                        .addComponent(jDateChooserInDate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(322, 322, 322))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonCheque)
                            .addComponent(jRadioButtonCredit))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserInDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabellInvoiceNumber1)
                        .addComponent(jTextFieldlInvoiceNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelDate))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCusName)
                            .addComponent(jTextFieldCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInvoiceAddress)
                            .addComponent(jTextFieldInvoiceAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldInvoiceContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelInvoiceContact))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCategory)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelShowHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPurchasePrice)
                            .addComponent(jTextFieldPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCode)
                            .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelWarranty)
                                    .addComponent(jLabelSellingPrice))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldUnitPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanelItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jButtonAddList)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrint)
                    .addComponent(jButtonDelete))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotal))
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
     
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    public void totalChange(){
       Double x=Double.parseDouble(jTextFieldUnitPrice.getText())*Double.parseDouble(jTextFieldInvoiceQuantity.getText());
       jTextFieldTotal.setText(x.toString());
    }
    
    private void jRadioButtonCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCreditActionPerformed
       
        jDialog2.setSize(800,700);
        jDialog2.setVisible(true);
                                   
    }//GEN-LAST:event_jRadioButtonCreditActionPerformed

    private void jButtonAddListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddListActionPerformed
       
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        //model.addRow(new String[]{"1",jComboBoxCategory.getSelectedItem().toString(), jTextFieldInvoiceQuantity.getText().toString(), jTextFieldUnitPrice.getText(),jTextFieldBrandName.getText(), 
            //"amount",jComboBoxWarranty.getSelectedItem().toString()});
        
        //add data to jtable1 when select category name phone
        
        String phone="Phones";
        if(jComboBoxCategory.getSelectedItem().toString().equals(phone)){
            model.addRow(new String[]{"1",jComboBoxCategory.getSelectedItem().toString()+","+jTextFieldBrandName.getText(), "1", jTextFieldUnitPrice.getText(), 
            "amount",jComboBoxWarranty.getSelectedItem().toString(),jTextFieldInvoiceIME.getText(),jTextFieldlInvoiceModel.getText(),"",jTextFieldBrandName.getText(),jComboBoxCategory.getSelectedItem().toString(),"6"});
            
    
            jComboBoxCategory.setSelectedItem("");
            jTextFieldInvoiceIME.setText("");
            jTextFieldlInvoiceModel.setText("");
            jTextFieldBrandName.setText("");
            jTextFieldUnitPrice.setText("");
            jComboBoxWarranty.setSelectedItem("");
        
        }else{
            //add data to jtable1 when select category name phone
            
            model.addRow(new String[]{"1",jComboBoxCategory.getSelectedItem().toString()+","+jTextFieldItemName.getText(), jTextFieldInvoiceQuantity.getText().toString(), jTextFieldUnitPrice.getText(),
             "",jComboBoxWarranty.getSelectedItem().toString()," "," "," "," ",jComboBoxCategory.getSelectedItem().toString(),"1"});
            //jDateChooserInDate.setDate(null);
            jComboBoxCategory.setSelectedItem("");
            jTextFieldItemName.setText("");
            //jTextFieldPurchasePrice.setText("");
            jTextFieldUnitPrice.setText("");
            jTextFieldInvoiceQuantity.setText("");
            jComboBoxWarranty.setSelectedItem("");
        }
        
        // to calculate amount of the each  row
        
        for (int i=0; i<jTable1.getRowCount(); i++)
          
        {
                double quantity =Double.parseDouble(jTable1.getValueAt(i, 2).toString()) ;
                double unit_price = Double.parseDouble(jTable1.getValueAt(i, 3).toString());
                double amount=quantity*unit_price;
                jTable1.setValueAt(amount, i, 4);
                
                
            }
        
        
        //set the total value for total field
        
            Double temp=0.0;
            Double amount = null;
            for (int i=0; i<jTable1.getRowCount(); i++)
            {
                amount = (Double) jTable1.getValueAt(i, 4);
                temp=temp+amount;  
            }
                jTextFieldTotal.setText(String.valueOf(new Double(temp)));
               
                jTextFieldTotal.setEditable(false);
        
    }//GEN-LAST:event_jButtonAddListActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
      
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int numRows = jTable1.getSelectedRows().length;
        
        model.removeRow(jTable1.getSelectedRow());
       
        

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTextFieldCusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCusNameActionPerformed

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryActionPerformed
        selectCategory();
       
    }//GEN-LAST:event_jComboBoxCategoryActionPerformed

    private void jTextFieldCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodeActionPerformed

    private void jComboBoxWarrantyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxWarrantyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxWarrantyActionPerformed

    private void jTextFieldBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBrandNameActionPerformed

    private void jTextFieldInvoiceQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInvoiceQuantityActionPerformed
        totalChange();
    }//GEN-LAST:event_jTextFieldInvoiceQuantityActionPerformed

    private void jTextFieldUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUnitPriceActionPerformed
       totalChange();
    }//GEN-LAST:event_jTextFieldUnitPriceActionPerformed

    private void jRadioButtonChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonChequeActionPerformed
        jDialog1.setSize(800,700);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jRadioButtonChequeActionPerformed

    private void jTextFieldPurchasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPurchasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPurchasePriceActionPerformed

    private void jTextFieldInvoiceIMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInvoiceIMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInvoiceIMEActionPerformed

    
   
    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        
        Connection          con                 = null;
        PreparedStatement   invoicePs           = null;
        PreparedStatement   invoiceRecordPs     = null;
        
        List<PreparedStatement> psList          = new ArrayList<PreparedStatement>();
        
        String      invoiceQuery = "INSERT INTO invoice (invoice_number, invoice_date, customer_name, contact_number, address, total_amount, invoice_type) " +
                                   "VALUES (?, ?, ?, ?, ?, ?, ?)";
        
        String invoice_number=jTextFieldlInvoiceNumber1.getText();
        Date invoice_date=jDateChooserInDate.getDate();
        String customer_name=jTextFieldCusName.getText();
        String contact_number=jTextFieldInvoiceContact.getText();
        String address=jTextFieldInvoiceAddress.getText();
        //Double total_amount=jTextFieldTotal.getText();
        double total_amount = Double.parseDouble(jTextFieldTotal.getText());
        String item_name=jTextFieldItemName.getText();
        String Imei_number=jTextFieldInvoiceIME.getText().toString();
        int category_id=jComboBoxCategory.getSelectedIndex();
       // Double unit_price=Double.parseDouble(jTextFieldUnitPrice.getText());
       // int quantity= Integer.parseInt(jTextFieldInvoiceQuantity.getText());
        int warranty_type_code=jComboBoxWarranty.getSelectedIndex();
    
        
    
        try {
            
            con = DB.getCon(); //get data from database
            
            con.setAutoCommit(false);
            
            invoicePs = con.prepareStatement(invoiceQuery, Statement.RETURN_GENERATED_KEYS);
            
            invoicePs.setString(1, invoice_number);
            invoicePs.setDate(2, new java.sql.Date(invoice_date.getTime()));
            invoicePs.setString(3, customer_name);
            invoicePs.setString(4, contact_number);
            invoicePs.setString(5, address);
            invoicePs.setDouble(6, total_amount);
            invoicePs.setInt(7, 1);
            
            psList.add(invoicePs);
            
            invoicePs.executeUpdate(); // Query is not yet commited
            
            ResultSet generatedKeys = invoicePs.getGeneratedKeys();
            
            if (generatedKeys.next()) {
                
                Integer insertedInvoiceId = generatedKeys.getInt(1);
                
                for (int i=0; i<jTable1.getRowCount(); i++) {
                    
                    String no = (String) jTable1.getValueAt(i, 0);
                    String description = (String) jTable1.getValueAt(i, 1);
                    int quantityJTable1 = Integer.parseInt(((String) jTable1.getValueAt(i, 2)) );
                    double unit_priceJTable1 = Double.parseDouble((String) jTable1.getValueAt(i, 3));
                    Double amount = (Double) jTable1.getValueAt(i, 4);
                    String warranty = (String) jTable1.getValueAt(i, 5);
                    String IMEI_number = (String) jTable1.getValueAt(i, 6);
                    String model_JTable = (String) jTable1.getValueAt(i, 7);
                    String Brand_JTable = (String) jTable1.getValueAt(i, 8);
                    String item_Name_JTable = (String) jTable1.getValueAt(i, 9);
                    String Category_id_JTable = (String) jTable1.getValueAt(i, 10);
                    int category_id1=jComboBoxCategory.getSelectedIndex();
                    
                    String phone = "Phones";
                    String item=Category_id_JTable;
                    String phoneRecordQuery =null;
                    String invoiceRecordQuery;
                    
                    if (phone.equals(item)) {
                        
                        // TODO
                        
                    } else {
                        
                        invoiceRecordQuery = "INSERT INTO invoice_record(invoice_id, item_nmber, category, item_name, unit_price, quantity, warranty_type_code) " +
                                            "values(?, ?, ?, ?, ?, ?, ?)";
                        
                        invoiceRecordPs = con.prepareStatement(invoiceRecordQuery);
                        
                        invoiceRecordPs.setInt(1, insertedInvoiceId);
                        invoiceRecordPs.setString(2, no);
                        invoiceRecordPs.setString(3, String.valueOf(category_id));
                        invoiceRecordPs.setString(4, String.valueOf(category_id1));
                        invoiceRecordPs.setDouble(5, unit_priceJTable1);
                        invoiceRecordPs.setInt(6, quantityJTable1);
                        invoiceRecordPs.setString(7, String.valueOf(warranty_type_code));
                        
                        psList.add(invoiceRecordPs);
                        
                        invoiceRecordPs.executeUpdate(); // Query is not yet commited
                    }
                }
                
                con.commit(); // Commit all changes
                
                jTextFieldInvoiceNumber.setText("");
                jTextFieldCusName.setText("");
                jTextFieldInvoiceAddress.setText("");
                jTextFieldInvoiceContact.setText("");
                
            } else {
                
                throw new RuntimeException("Invoice is not updted");
                
            }
        
        }
        catch (SQLException e) {
            e.printStackTrace();
            // Roll back all the changes with above queries
            if (con != null)
            {
                try {
                    con.rollback();
                }
                catch (SQLException ex) {
                    // Roll back messed up
                    ex.printStackTrace();
                }
                
            }
            
        }
        catch (Exception e) {
            
            // Something is not correctly handle
            e.printStackTrace();
        }
        finally {
            // Okay, now we close all the PreparedStatements
            try {
                for (PreparedStatement ps : psList) {
                    ps.close();
                }
            }
            catch (SQLException e) {
                // Something is not correctly handle
                e.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jTextFieldlInvoiceNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldlInvoiceNumber1ActionPerformed
        //jTextFieldlInvoiceNumber1
    }//GEN-LAST:event_jTextFieldlInvoiceNumber1ActionPerformed
// this method couldnt checked because column count error
    public static void removeAllDataFromJTable(JTable jTable1) {
     f=false;
    int numberOfRows = jTable1.getRowCount();
    int numberOfColumns = jTable1.getColumnCount();
    int rowCounter = 0;
    int columnCounter = 0;
    //we will travel to every row and clean it
    for (rowCounter = 0; rowCounter < numberOfRows; rowCounter++) {
        for (columnCounter = 0; columnCounter < numberOfColumns; columnCounter++) {
            jTable1.setValueAt(null, rowCounter, columnCounter);
        }
    }
}
    
    
    public void selectCategory(){
    
        String phone = "Phones";
        String item=jComboBoxCategory.getSelectedItem().toString();
       
           System.out.println(item);
        if(item.equals(phone)){
              
              jPanelShowHide.setVisible(true);
              jPanelItem.setVisible(false);
              jPanelQuantity.setVisible(false);
              
          }else{
          jPanelShowHide.setVisible(false);
          jPanelItem.setVisible(true);
          jPanelQuantity.setVisible(true);
          }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddList;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JComboBox jComboBoxCategory;
    private javax.swing.JComboBox jComboBoxWarranty;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooserInDate;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabeChequeOtherDetails;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBrandName;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelCusName;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelInvoiceAddress;
    private javax.swing.JLabel jLabelInvoiceContact;
    private javax.swing.JLabel jLabelInvoiceIME;
    private javax.swing.JLabel jLabelInvoiceModel;
    private javax.swing.JLabel jLabelInvoiceNumber;
    private javax.swing.JLabel jLabelInvoiceQuantity;
    private javax.swing.JLabel jLabelItemName;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPurchasePrice;
    private javax.swing.JLabel jLabelSellingPrice;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelWarranty;
    private javax.swing.JLabel jLabellInvoiceNumber1;
    private javax.swing.JPanel jPanelItem;
    private javax.swing.JPanel jPanelQuantity;
    private javax.swing.JPanel jPanelShowHide;
    private javax.swing.JRadioButton jRadioButtonCheque;
    private javax.swing.JRadioButton jRadioButtonCredit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldBrandName;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldCusName;
    private javax.swing.JTextField jTextFieldInvoiceAddress;
    private javax.swing.JTextField jTextFieldInvoiceContact;
    private javax.swing.JTextField jTextFieldInvoiceIME;
    private javax.swing.JTextField jTextFieldInvoiceNumber;
    private javax.swing.JTextField jTextFieldInvoiceQuantity;
    private javax.swing.JTextField jTextFieldItemName;
    private javax.swing.JTextField jTextFieldPurchasePrice;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldUnitPrice;
    private javax.swing.JTextField jTextFieldlInvoiceModel;
    private javax.swing.JTextField jTextFieldlInvoiceNumber1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
