/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycom.mytest1.view;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kaushika
 */
public class PurchaseManager extends javax.swing.JPanel {

    /**
     * Creates new form PurchaseManager
     */
    public PurchaseManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelPPurchase = new javax.swing.JLabel();
        jDateChooserPurDate = new com.toedter.calendar.JDateChooser();
        jLabelPurDate = new javax.swing.JLabel();
        jLabelCompName = new javax.swing.JLabel();
        jLabelPurCategory = new javax.swing.JLabel();
        jComboBoxPurCategory = new javax.swing.JComboBox();
        jLabelPurEMI = new javax.swing.JLabel();
        jTextFieldPurEMI = new javax.swing.JTextField();
        jLabelPurQuantity = new javax.swing.JLabel();
        jTextFieldPurQuantity = new javax.swing.JTextField();
        jLabelPurUnitPrice = new javax.swing.JLabel();
        jTextFieldPurUnitPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePurTable = new javax.swing.JTable();
        jButtonpurClear = new javax.swing.JButton();
        jButtonPurSave = new javax.swing.JButton();
        jLabelPurTotal = new javax.swing.JLabel();
        jTextFieldPurTotal = new javax.swing.JTextField();
        jButtonAddPurchase = new javax.swing.JButton();
        jComboBoxCompName = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelOtherCategory = new javax.swing.JLabel();
        jLabelOtherItemName = new javax.swing.JLabel();
        jComboBoxOtherItemName = new javax.swing.JComboBox();
        jLabelOtherQuantity = new javax.swing.JLabel();
        jTextFieldOtherQuantity = new javax.swing.JTextField();
        jLabelOtherUnitPrice = new javax.swing.JLabel();
        jTextFieldOtherUnitPrice = new javax.swing.JTextField();
        jComboBoxOtherCategory = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOtherPurchase = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabelPurBrandName = new javax.swing.JLabel();
        jTextFieldPurBrandName = new javax.swing.JTextField();
        jLabelModelName = new javax.swing.JLabel();
        jTextFieldlModelName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        jLabelPPurchase.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPPurchase.setText("Purchase");

        jLabelPurDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurDate.setText("Date");

        jLabelCompName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCompName.setText("Company Name");

        jLabelPurCategory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurCategory.setText("Category");

        jComboBoxPurCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelPurEMI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurEMI.setText("EMI Number");

        jLabelPurQuantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurQuantity.setText("Quantity");

        jTextFieldPurQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPurQuantityActionPerformed(evt);
            }
        });

        jLabelPurUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurUnitPrice.setText("Unit Price");

        jTextFieldPurUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPurUnitPriceActionPerformed(evt);
            }
        });

        jTablePurTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Category", "Brand Name", "Company Name", "Quantity", "EMI Number", "Unit Price"
            }
        ));
        jScrollPane1.setViewportView(jTablePurTable);

        jButtonpurClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonpurClear.setText("Clear Records");
        jButtonpurClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpurClearActionPerformed(evt);
            }
        });

        jButtonPurSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPurSave.setText("Save");

        jLabelPurTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurTotal.setText("Total");

        jButtonAddPurchase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAddPurchase.setText("Add To Stock");
        jButtonAddPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPurchaseActionPerformed(evt);
            }
        });

        jComboBoxCompName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Phone");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Other");

        jLabelOtherCategory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOtherCategory.setText("Category");

        jLabelOtherItemName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOtherItemName.setText("Item Name");

        jComboBoxOtherItemName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelOtherQuantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOtherQuantity.setText("Quantity");

        jLabelOtherUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOtherUnitPrice.setText("Unit Price");

        jComboBoxOtherCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOtherCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBoxOtherCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelOtherItemName, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jComboBoxOtherItemName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelOtherQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addGap(104, 104, 104))
                    .addComponent(jTextFieldOtherQuantity))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelOtherUnitPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jTextFieldOtherUnitPrice))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOtherCategory)
                    .addComponent(jLabelOtherItemName)
                    .addComponent(jLabelOtherQuantity)
                    .addComponent(jLabelOtherUnitPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOtherItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOtherQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOtherUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOtherCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTableOtherPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Category", "Item Name", "Company Name", "Quantity", "Unit Price"
            }
        ));
        jScrollPane2.setViewportView(jTableOtherPurchase);

        jLabelPurBrandName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurBrandName.setText("Brand Name");

        jTextFieldPurBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPurBrandNameActionPerformed(evt);
            }
        });

        jLabelModelName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelModelName.setText("Model Name");

        jTextFieldlModelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldlModelNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPurBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPurBrandName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldlModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelModelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabelPurBrandName)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPurBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldlModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelPurTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldPurTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonpurClear))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(jButtonPurSave, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(700, 700, 700))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(496, 496, 496)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(106, 106, 106))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabelPPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jComboBoxPurCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelPurDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jDateChooserPurDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(jLabelPurCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(10, 10, 10)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(41, 41, 41)
                                                    .addComponent(jLabelCompName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(152, 152, 152)
                                                    .addComponent(jRadioButton1)
                                                    .addGap(54, 54, 54)
                                                    .addComponent(jRadioButton2))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jComboBoxCompName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(30, 30, 30)
                                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabelPurEMI, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextFieldPurEMI, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(35, 35, 35)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextFieldPurQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabelPurQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextFieldPurUnitPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabelPurUnitPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addComponent(jButtonAddPurchase)
                            .addGap(2, 2, 2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelPPurchase)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPurDate)
                    .addComponent(jLabelCompName)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserPurDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCompName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddPurchase)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPurEMI)
                            .addComponent(jLabelPurUnitPrice)
                            .addComponent(jLabelPurQuantity))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabelPurCategory)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldPurQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldPurUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxPurCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldPurEMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(52, 52, 52)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jButtonpurClear))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPurTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPurTotal))
                .addGap(5, 5, 5)
                .addComponent(jButtonPurSave)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPurBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPurBrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPurBrandNameActionPerformed

    private void jTextFieldPurQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPurQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPurQuantityActionPerformed

    private void jButtonAddPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPurchaseActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTablePurTable.getModel();
        
         model.addRow(new String[]{jDateChooserPurDate.getDate().toString(),jComboBoxPurCategory.getSelectedItem().toString(), jTextFieldPurBrandName.getText(), jComboBoxCompName.getSelectedItem().toString(), 
            jTextFieldPurQuantity.getText().toString(), jTextFieldPurEMI.getText(),jTextFieldPurUnitPrice.getText()});
         
            jDateChooserPurDate.setDate(null);
            jComboBoxPurCategory.setSelectedItem("");
            jTextFieldPurBrandName.setText("");
            jComboBoxCompName.setSelectedItem("");
            jTextFieldPurQuantity.setText("");
            jTextFieldPurEMI.setText("");
            jTextFieldPurUnitPrice.setText("");
            
    }//GEN-LAST:event_jButtonAddPurchaseActionPerformed

    private void jTextFieldPurUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPurUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPurUnitPriceActionPerformed

    private void jButtonpurClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpurClearActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTablePurTable.getModel();
        int numRows = jTablePurTable.getSelectedRows().length;
        
        model.removeRow(jTablePurTable.getSelectedRow());
    }//GEN-LAST:event_jButtonpurClearActionPerformed

    private void jTextFieldlModelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldlModelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldlModelNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAddPurchase;
    private javax.swing.JButton jButtonPurSave;
    private javax.swing.JButton jButtonpurClear;
    private javax.swing.JComboBox jComboBoxCompName;
    private javax.swing.JComboBox jComboBoxOtherCategory;
    private javax.swing.JComboBox jComboBoxOtherItemName;
    private javax.swing.JComboBox jComboBoxPurCategory;
    private com.toedter.calendar.JDateChooser jDateChooserPurDate;
    private javax.swing.JLabel jLabelCompName;
    private javax.swing.JLabel jLabelModelName;
    private javax.swing.JLabel jLabelOtherCategory;
    private javax.swing.JLabel jLabelOtherItemName;
    private javax.swing.JLabel jLabelOtherQuantity;
    private javax.swing.JLabel jLabelOtherUnitPrice;
    private javax.swing.JLabel jLabelPPurchase;
    private javax.swing.JLabel jLabelPurBrandName;
    private javax.swing.JLabel jLabelPurCategory;
    private javax.swing.JLabel jLabelPurDate;
    private javax.swing.JLabel jLabelPurEMI;
    private javax.swing.JLabel jLabelPurQuantity;
    private javax.swing.JLabel jLabelPurTotal;
    private javax.swing.JLabel jLabelPurUnitPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableOtherPurchase;
    private javax.swing.JTable jTablePurTable;
    private javax.swing.JTextField jTextFieldOtherQuantity;
    private javax.swing.JTextField jTextFieldOtherUnitPrice;
    private javax.swing.JTextField jTextFieldPurBrandName;
    private javax.swing.JTextField jTextFieldPurEMI;
    private javax.swing.JTextField jTextFieldPurQuantity;
    private javax.swing.JTextField jTextFieldPurTotal;
    private javax.swing.JTextField jTextFieldPurUnitPrice;
    private javax.swing.JTextField jTextFieldlModelName;
    // End of variables declaration//GEN-END:variables
}
