/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycom.mytest1.view;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kaushika
 */
public class PurchaseM extends javax.swing.JPanel {

    /**
     * Creates new form PurchaseM
     */
    public PurchaseM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCompName = new javax.swing.JComboBox();
        jDateChooserPurDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePurTable2 = new javax.swing.JTable();
        jComboBoxPurCategory = new javax.swing.JComboBox();
        jLabelPurCategory = new javax.swing.JLabel();
        jLabelPurBrandName = new javax.swing.JLabel();
        jTextFieldPurBrandName = new javax.swing.JTextField();
        jLabelModelName = new javax.swing.JLabel();
        jTextFieldlModelName = new javax.swing.JTextField();
        jLabelPurEMI = new javax.swing.JLabel();
        jTextFieldPurEMI = new javax.swing.JTextField();
        jLabelPurQuantity = new javax.swing.JLabel();
        jTextFieldPurQuantity = new javax.swing.JTextField();
        jLabelPurUnitPrice = new javax.swing.JLabel();
        jTextFieldPurUnitPrice = new javax.swing.JTextField();
        jButtonAddPurchase = new javax.swing.JButton();
        jButtonpurClear = new javax.swing.JButton();
        jLabelPurTotal = new javax.swing.JLabel();
        jTextFieldPurTotal = new javax.swing.JTextField();
        jButtonPurSave = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelOtherCategory = new javax.swing.JLabel();
        jComboBoxOtherCategory = new javax.swing.JComboBox();
        jLabelOtherPurDate = new javax.swing.JLabel();
        jDateChooserOtherPurDate = new com.toedter.calendar.JDateChooser();
        jLabelOtherPurCompName = new javax.swing.JLabel();
        jComboBoxOtherPurCompName = new javax.swing.JComboBox();
        jLabelOtherItemName = new javax.swing.JLabel();
        jComboBoxOtherItemName = new javax.swing.JComboBox();
        jLabelOtherQuantity = new javax.swing.JLabel();
        jLabelOtherUnitPrice = new javax.swing.JLabel();
        jTextFieldOtherUnitPrice = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOtherPurchase = new javax.swing.JTable();
        jButtonAddPurchase1 = new javax.swing.JButton();
        jTextFieldOtherPurQuantity = new javax.swing.JTextField();
        jButtonPurSave1 = new javax.swing.JButton();
        jLabelPurTotal1 = new javax.swing.JLabel();
        jTextFieldPurTotal1 = new javax.swing.JTextField();
        jButtonpurClear1 = new javax.swing.JButton();

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setText("Company Name");

        jComboBoxCompName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Date");

        jTablePurTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Category", "Brand Name", "Company Name", "Quantity", "EMI Number", "Unit Price"
            }
        ));
        jScrollPane1.setViewportView(jTablePurTable2);

        jComboBoxPurCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelPurCategory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurCategory.setText("Category");

        jLabelPurBrandName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurBrandName.setText("Brand Name");

        jTextFieldPurBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPurBrandNameActionPerformed(evt);
            }
        });

        jLabelModelName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelModelName.setText("Model Name");

        jTextFieldlModelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldlModelNameActionPerformed(evt);
            }
        });

        jLabelPurEMI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurEMI.setText("EMI Number");

        jLabelPurQuantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurQuantity.setText("Quantity");

        jTextFieldPurQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPurQuantityActionPerformed(evt);
            }
        });

        jLabelPurUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurUnitPrice.setText("Unit Price");

        jTextFieldPurUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPurUnitPriceActionPerformed(evt);
            }
        });

        jButtonAddPurchase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAddPurchase.setText("Add To Stock");
        jButtonAddPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPurchaseActionPerformed(evt);
            }
        });

        jButtonpurClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonpurClear.setText("Clear Records");
        jButtonpurClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpurClearActionPerformed(evt);
            }
        });

        jLabelPurTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurTotal.setText("Total");

        jButtonPurSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPurSave.setText("Save");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelPurCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(32, 32, 32)))
                    .addComponent(jComboBoxPurCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxCompName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserPurDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPurBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPurBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldPurEMI, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPurEMI, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelModelName, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addGap(344, 344, 344))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldlModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPurUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPurUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonPurSave, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonpurClear)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jLabelPurTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldPurTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPurQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPurQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(jButtonAddPurchase)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserPurDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBoxCompName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPurCategory)
                    .addComponent(jLabelPurBrandName)
                    .addComponent(jLabelModelName)
                    .addComponent(jLabelPurUnitPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldlModelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPurUnitPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxPurCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPurBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddPurchase)
                        .addComponent(jTextFieldPurEMI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPurEMI)
                        .addComponent(jTextFieldPurQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonpurClear)
                    .addComponent(jLabelPurQuantity))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPurTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPurTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jButtonPurSave)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Phones Purchase", jPanel1);

        jLabelOtherCategory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOtherCategory.setText("Category");

        jComboBoxOtherCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelOtherPurDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOtherPurDate.setText("Date");

        jLabelOtherPurCompName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOtherPurCompName.setText("Company Name");

        jComboBoxOtherPurCompName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxOtherPurCompName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOtherPurCompNameActionPerformed(evt);
            }
        });

        jLabelOtherItemName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOtherItemName.setText("Item Name");

        jComboBoxOtherItemName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelOtherQuantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOtherQuantity.setText("Quantity");

        jLabelOtherUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOtherUnitPrice.setText("Unit Price");

        jTableOtherPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Category", "Item Name", "Company Name", "Quantity", "Unit Price"
            }
        ));
        jScrollPane2.setViewportView(jTableOtherPurchase);

        jButtonAddPurchase1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAddPurchase1.setText("Add To Stock");
        jButtonAddPurchase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPurchase1ActionPerformed(evt);
            }
        });

        jButtonPurSave1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPurSave1.setText("Save");

        jLabelPurTotal1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurTotal1.setText("Total");

        jButtonpurClear1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonpurClear1.setText("Clear Records");
        jButtonpurClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpurClear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOtherPurCompName)
                            .addComponent(jLabelOtherCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxOtherCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBoxOtherItemName, javax.swing.GroupLayout.Alignment.LEADING, 0, 124, Short.MAX_VALUE)
                                    .addComponent(jComboBoxOtherPurCompName, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(jLabelOtherPurDate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateChooserOtherPurDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jTextFieldOtherPurQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelOtherItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabelOtherQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelOtherUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldOtherUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelPurTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPurTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonPurSave1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonpurClear1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAddPurchase1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOtherPurCompName)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelOtherPurDate)
                            .addComponent(jDateChooserOtherPurDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxOtherPurCompName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOtherCategory)
                            .addComponent(jLabelOtherItemName)
                            .addComponent(jLabelOtherQuantity)
                            .addComponent(jLabelOtherUnitPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOtherPurQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldOtherUnitPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxOtherCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxOtherItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12)
                .addComponent(jButtonAddPurchase1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonpurClear1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPurTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPurTotal1))
                .addGap(18, 18, 18)
                .addComponent(jButtonPurSave1)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Other Purchase", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPurBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPurBrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPurBrandNameActionPerformed

    private void jTextFieldlModelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldlModelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldlModelNameActionPerformed

    private void jTextFieldPurQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPurQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPurQuantityActionPerformed

    private void jTextFieldPurUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPurUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPurUnitPriceActionPerformed

    private void jButtonAddPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPurchaseActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTablePurTable2.getModel();

        model.addRow(new String[]{jDateChooserPurDate.getDate().toString(),jComboBoxPurCategory.getSelectedItem().toString(), jTextFieldPurBrandName.getText(), jComboBoxCompName.getSelectedItem().toString(),
            jTextFieldPurQuantity.getText().toString(), jTextFieldPurEMI.getText(),jTextFieldPurUnitPrice.getText()});

    jDateChooserPurDate.setDate(null);
    jComboBoxPurCategory.setSelectedItem("");
    jTextFieldPurBrandName.setText("");
    jComboBoxCompName.setSelectedItem("");
    jTextFieldPurQuantity.setText("");
    jTextFieldPurEMI.setText("");
    jTextFieldPurUnitPrice.setText("");

    }//GEN-LAST:event_jButtonAddPurchaseActionPerformed

    private void jButtonpurClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpurClearActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTablePurTable2.getModel();
        int numRows = jTablePurTable2.getSelectedRows().length;

        model.removeRow(jTablePurTable2.getSelectedRow());
    }//GEN-LAST:event_jButtonpurClearActionPerformed

    private void jButtonAddPurchase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPurchase1ActionPerformed
           DefaultTableModel model = (DefaultTableModel) jTableOtherPurchase.getModel();

        model.addRow(new String[]{jDateChooserOtherPurDate.getDate().toString(),jComboBoxOtherCategory.getSelectedItem().toString(),jComboBoxOtherItemName.getSelectedItem().toString(),jComboBoxOtherPurCompName.getSelectedItem().toString(), jTextFieldOtherPurQuantity.getText(), 
             jTextFieldOtherUnitPrice.getText()});

        jDateChooserOtherPurDate.setDate(null);
        jComboBoxOtherCategory.setSelectedItem("");
        jComboBoxOtherItemName.setSelectedItem("");
        jComboBoxOtherPurCompName.setSelectedItem("");
        jTextFieldOtherPurQuantity.setText("");
        jTextFieldOtherUnitPrice.setText("");
        
        //jComboBoxCompName.setSelectedItem("");
        
        //jTextFieldPurEMI.setText("");
        
    }//GEN-LAST:event_jButtonAddPurchase1ActionPerformed

    private void jButtonpurClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpurClear1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableOtherPurchase.getModel();
        int numRows = jTableOtherPurchase.getSelectedRows().length;

        model.removeRow(jTableOtherPurchase.getSelectedRow());
    }//GEN-LAST:event_jButtonpurClear1ActionPerformed

    private void jComboBoxOtherPurCompNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOtherPurCompNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOtherPurCompNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPurchase;
    private javax.swing.JButton jButtonAddPurchase1;
    private javax.swing.JButton jButtonPurSave;
    private javax.swing.JButton jButtonPurSave1;
    private javax.swing.JButton jButtonpurClear;
    private javax.swing.JButton jButtonpurClear1;
    private javax.swing.JComboBox jComboBoxCompName;
    private javax.swing.JComboBox jComboBoxOtherCategory;
    private javax.swing.JComboBox jComboBoxOtherItemName;
    private javax.swing.JComboBox jComboBoxOtherPurCompName;
    private javax.swing.JComboBox jComboBoxPurCategory;
    private com.toedter.calendar.JDateChooser jDateChooserOtherPurDate;
    private com.toedter.calendar.JDateChooser jDateChooserPurDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelModelName;
    private javax.swing.JLabel jLabelOtherCategory;
    private javax.swing.JLabel jLabelOtherItemName;
    private javax.swing.JLabel jLabelOtherPurCompName;
    private javax.swing.JLabel jLabelOtherPurDate;
    private javax.swing.JLabel jLabelOtherQuantity;
    private javax.swing.JLabel jLabelOtherUnitPrice;
    private javax.swing.JLabel jLabelPurBrandName;
    private javax.swing.JLabel jLabelPurCategory;
    private javax.swing.JLabel jLabelPurEMI;
    private javax.swing.JLabel jLabelPurQuantity;
    private javax.swing.JLabel jLabelPurTotal;
    private javax.swing.JLabel jLabelPurTotal1;
    private javax.swing.JLabel jLabelPurUnitPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableOtherPurchase;
    private javax.swing.JTable jTablePurTable2;
    private javax.swing.JTextField jTextFieldOtherPurQuantity;
    private javax.swing.JTextField jTextFieldOtherUnitPrice;
    private javax.swing.JTextField jTextFieldPurBrandName;
    private javax.swing.JTextField jTextFieldPurEMI;
    private javax.swing.JTextField jTextFieldPurQuantity;
    private javax.swing.JTextField jTextFieldPurTotal;
    private javax.swing.JTextField jTextFieldPurTotal1;
    private javax.swing.JTextField jTextFieldPurUnitPrice;
    private javax.swing.JTextField jTextFieldlModelName;
    // End of variables declaration//GEN-END:variables
}
