/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycom.mytest1.view;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kaushika
 */
public class PurchaseManager1 extends javax.swing.JPanel {

    /**
     * Creates new form PurchaseManager1
     */
    public PurchaseManager1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogPurchaseDetails = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabelCompanyName = new javax.swing.JLabel();
        jTextFieldCompanyName = new javax.swing.JTextField();
        jLabelContactPerson = new javax.swing.JLabel();
        jTextFieldContactPerson = new javax.swing.JTextField();
        jLabelTPNumber = new javax.swing.JLabel();
        jTextFieldTPNumber = new javax.swing.JTextField();
        jLabelSupplierEmail = new javax.swing.JLabel();
        jTextFieldSupplierEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCompName = new javax.swing.JComboBox();
        jComboBoxPurCategory = new javax.swing.JComboBox();
        jLabelPurCategory = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserPurDate = new com.toedter.calendar.JDateChooser();
        jLabelPurBrandName = new javax.swing.JLabel();
        jTextFieldPurBrandName = new javax.swing.JTextField();
        jLabelModelName = new javax.swing.JLabel();
        jTextFieldlModelName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelPurEMI = new javax.swing.JLabel();
        jTextFieldPurEMI = new javax.swing.JTextField();
        jLabelPurQuantity = new javax.swing.JLabel();
        jTextFieldPurQuantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePurTable2 = new javax.swing.JTable();
        jLabelPurUnitPrice = new javax.swing.JLabel();
        jTextFieldPurUnitPrice = new javax.swing.JTextField();
        jButtonAddPurchase = new javax.swing.JButton();
        jButtonpurClear = new javax.swing.JButton();
        jLabelPurTotal = new javax.swing.JLabel();
        jTextFieldPurTotal = new javax.swing.JTextField();
        jButtonPurSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Add New Supplier");

        jLabelCompanyName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCompanyName.setText("Company Name");

        jLabelContactPerson.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelContactPerson.setText("Contact Person");

        jLabelTPNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTPNumber.setText("TP Number");

        jLabelSupplierEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSupplierEmail.setText("Email");

        jTextFieldSupplierEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSupplierEmailActionPerformed(evt);
            }
        });

        jButton1.setText("Add To Suppliers");

        javax.swing.GroupLayout jDialogPurchaseDetailsLayout = new javax.swing.GroupLayout(jDialogPurchaseDetails.getContentPane());
        jDialogPurchaseDetails.getContentPane().setLayout(jDialogPurchaseDetailsLayout);
        jDialogPurchaseDetailsLayout.setHorizontalGroup(
            jDialogPurchaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPurchaseDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogPurchaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogPurchaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(jDialogPurchaseDetailsLayout.createSequentialGroup()
                            .addGroup(jDialogPurchaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelSupplierEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTPNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelContactPerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCompanyName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                            .addGap(38, 38, 38)
                            .addGroup(jDialogPurchaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                .addComponent(jTextFieldContactPerson)
                                .addComponent(jTextFieldTPNumber)
                                .addComponent(jTextFieldSupplierEmail)))))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jDialogPurchaseDetailsLayout.setVerticalGroup(
            jDialogPurchaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPurchaseDetailsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(jDialogPurchaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCompanyName)
                    .addComponent(jTextFieldCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogPurchaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContactPerson)
                    .addComponent(jTextFieldContactPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogPurchaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTPNumber)
                    .addComponent(jTextFieldTPNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogPurchaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSupplierEmail)
                    .addComponent(jTextFieldSupplierEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Company Name");

        jComboBoxCompName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Softlogic plc", "Huwavi", "Brantel", "Add New" }));
        jComboBoxCompName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCompNameActionPerformed(evt);
            }
        });

        jComboBoxPurCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Phones", "Charger", "Battery", "Head Phone", "Phone Pouch", "Phone Housing" }));
        jComboBoxPurCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPurCategoryActionPerformed(evt);
            }
        });

        jLabelPurCategory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurCategory.setText("Category");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Date");

        jLabelPurBrandName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurBrandName.setText("Brand Name");

        jTextFieldPurBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPurBrandNameActionPerformed(evt);
            }
        });

        jLabelModelName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelModelName.setText("Model Name");

        jTextFieldlModelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldlModelNameActionPerformed(evt);
            }
        });

        jLabelPurEMI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurEMI.setText("EMI Number");

        jLabelPurQuantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurQuantity.setText("Quantity");

        jTextFieldPurQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPurQuantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelPurEMI, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jLabelPurQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldPurEMI, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPurQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelPurQuantity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPurQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelPurEMI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPurEMI, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        jTablePurTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Category", "Brand Name", "Company Name", "Quantity", "EMI Number", "Unit Price"
            }
        ));
        jScrollPane1.setViewportView(jTablePurTable2);

        jLabelPurUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurUnitPrice.setText("Unit Price");

        jTextFieldPurUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPurUnitPriceActionPerformed(evt);
            }
        });

        jButtonAddPurchase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAddPurchase.setText("Add To Stock");
        jButtonAddPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPurchaseActionPerformed(evt);
            }
        });

        jButtonpurClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonpurClear.setText("Clear Records");
        jButtonpurClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpurClearActionPerformed(evt);
            }
        });

        jLabelPurTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPurTotal.setText("Total");

        jButtonPurSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPurSave.setText("Save");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Purchase Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldPurBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addComponent(jLabelPurBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldlModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelModelName, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelPurCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxPurCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateChooserPurDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxCompName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPurUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPurUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121)))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddPurchase, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelPurTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jTextFieldPurTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonPurSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonpurClear, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxCompName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPurUnitPrice)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jDateChooserPurDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPurCategory)
                                    .addComponent(jLabelPurBrandName)
                                    .addComponent(jLabelModelName))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPurCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPurBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldlModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPurUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jButtonAddPurchase))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonpurClear)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPurTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPurTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPurSave)
                .addGap(336, 336, 336))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPurBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPurBrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPurBrandNameActionPerformed

    private void jTextFieldlModelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldlModelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldlModelNameActionPerformed

    private void jTextFieldPurQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPurQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPurQuantityActionPerformed

    private void jTextFieldPurUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPurUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPurUnitPriceActionPerformed

    private void jButtonAddPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPurchaseActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTablePurTable2.getModel();

        model.addRow(new String[]{jDateChooserPurDate.getDate().toString(),jComboBoxPurCategory.getSelectedItem().toString(), jTextFieldPurBrandName.getText(), jComboBoxCompName.getSelectedItem().toString(),
            jTextFieldPurQuantity.getText().toString(), jTextFieldPurEMI.getText(),jTextFieldPurUnitPrice.getText()});

    jDateChooserPurDate.setDate(null);
    jComboBoxPurCategory.setSelectedItem("");
    jTextFieldPurBrandName.setText("");
    jComboBoxCompName.setSelectedItem("");
    jTextFieldPurQuantity.setText("");
    jTextFieldPurEMI.setText("");
    jTextFieldPurUnitPrice.setText("");
    }//GEN-LAST:event_jButtonAddPurchaseActionPerformed

    private void jButtonpurClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpurClearActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTablePurTable2.getModel();
        int numRows = jTablePurTable2.getSelectedRows().length;

        model.removeRow(jTablePurTable2.getSelectedRow());
    }//GEN-LAST:event_jButtonpurClearActionPerformed

    private void jComboBoxPurCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPurCategoryActionPerformed
      
         String item1=jComboBoxPurCategory.getSelectedItem().toString();
        String phone="";
         
         if(item1==phone){
        jPanel2.setVisible(true);
       } else{
         jPanel2.setVisible(false);
         }
       
    }//GEN-LAST:event_jComboBoxPurCategoryActionPerformed

    private void jTextFieldSupplierEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupplierEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupplierEmailActionPerformed

    private void jComboBoxCompNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCompNameActionPerformed
        String Addnew =jComboBoxCompName.getSelectedItem().toString();
        if(Addnew=="Add New"){
            jDialogPurchaseDetails.setVisible(true);
            jDialogPurchaseDetails.setSize(800,700);
        }
    }//GEN-LAST:event_jComboBoxCompNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddPurchase;
    private javax.swing.JButton jButtonPurSave;
    private javax.swing.JButton jButtonpurClear;
    private javax.swing.JComboBox jComboBoxCompName;
    private javax.swing.JComboBox jComboBoxPurCategory;
    private com.toedter.calendar.JDateChooser jDateChooserPurDate;
    private javax.swing.JDialog jDialogPurchaseDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCompanyName;
    private javax.swing.JLabel jLabelContactPerson;
    private javax.swing.JLabel jLabelModelName;
    private javax.swing.JLabel jLabelPurBrandName;
    private javax.swing.JLabel jLabelPurCategory;
    private javax.swing.JLabel jLabelPurEMI;
    private javax.swing.JLabel jLabelPurQuantity;
    private javax.swing.JLabel jLabelPurTotal;
    private javax.swing.JLabel jLabelPurUnitPrice;
    private javax.swing.JLabel jLabelSupplierEmail;
    private javax.swing.JLabel jLabelTPNumber;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePurTable2;
    private javax.swing.JTextField jTextFieldCompanyName;
    private javax.swing.JTextField jTextFieldContactPerson;
    private javax.swing.JTextField jTextFieldPurBrandName;
    private javax.swing.JTextField jTextFieldPurEMI;
    private javax.swing.JTextField jTextFieldPurQuantity;
    private javax.swing.JTextField jTextFieldPurTotal;
    private javax.swing.JTextField jTextFieldPurUnitPrice;
    private javax.swing.JTextField jTextFieldSupplierEmail;
    private javax.swing.JTextField jTextFieldTPNumber;
    private javax.swing.JTextField jTextFieldlModelName;
    // End of variables declaration//GEN-END:variables
}
